sudo: required
services:
  - docker
language: java
before_install: ant -buildfile ./GitProject/build.xml run
install:
- docker build .
- docker login -u pkondratiev -p l0govera hub.docker.com
- docker push 
