sudo: required
services:
  - docker
language: java
script: ant -buildfile ./GitProject/build.xml run
after_success:
- docker login -u "pkondratiev" -p "l0govera" cloud.docker.com
- docker build -f Dockerfile -t <repository_name> .
- docker push <repository_name>
