sudo: required
services:
  - docker
language: java
script: ant -buildfile ./GitProject/build.xml run
after_success:
- docker login -u "pkondratiev" -p "l0govera"
- docker build -f Dockerfile -t pkondratiev/test .
- docker push pkondratiev/test
